name: "Build Lacewing"
description: "Builds the Lacewing application"

inputs:
  target:
    description: "Cargo build target"
    required: true

runs:
  using: "composite"
  steps:
    - name: Install NPM dependencies
      run: npm ci
      shell: bash

    - name: Build static dependencies and components
      run: npm run release
      shell: bash

    - name: Build release binary
      run: cargo build --target ${{ inputs.target }} --verbose --release
      shell: bash
