version: '3.4'
services:

  db:
    image: postgres:14-alpine
    environment:
      POSTGRES_DB: lacewing
      POSTGRES_PASSWORD: testpassword
      POSTGRES_USER: postgres
    ports:
      - "5432:5432"
