name: "Database Migrations"
description: "Runs database migrations against an environment"

inputs:
  database_url:
    description: "Connection string for the database. 
    Follows the format: postgres:
    //[user[:password]@][host][:port][/dbname][?options]"
    required: true
    default: "postgres://root:password@localhost:5432/lacalhost?sslmode=disable"

runs:
  using: "composite"
  steps:
    - name: Install golang-migrate
      run: npm install -g dbmate
      shell: bash

    - name: Run database migrations
      env:
        DATABASE_URL: ${{ inputs.database_url }}
      run: dbmate up
      shell: bash
